// src/components/AgentPipelineModal.tsx
import React, { useState, useCallback, useRef } from 'react'
import { Loader2, CheckCircle, XCircle, ArrowRight, X, Brain, FileCheck, Lock, Activity, Settings } from 'lucide-react'

type AgentStep = 'Intelligence' | 'Compliance' | 'ZK' | 'Settlement' | 'Auditor'

const AGENT_STEPS: AgentStep[] = ['Intelligence', 'Compliance', 'ZK', 'Settlement', 'Auditor']

const STEP_ICONS: Record<AgentStep, React.ElementType> = {
  Intelligence: Activity,
  Compliance: FileCheck,
  ZK: Lock,
  Settlement: Settings,
  Auditor: Brain,
}

export default function AgentPipelineModal({
  onClose,
}: {
  onClose: () => void
}) {
  const [entityId, setEntityId] = useState('')
  const [chain, setChain] = useState<'stellar' | 'casper'>('stellar')
  const [policy, setPolicy] = useState('')
  const [running, setRunning] = useState(false)
  const [currentStep, setCurrentStep] = useState(-1)
  const [completedSteps, setCompletedSteps] = useState<AgentStep[]>([])
  const [log, setLog] = useState<string[]>([])
  const [result, setResult] = useState<{
    auditReport: string
    disclosureLabels: string[]
    onChainTxHash: string
  } | null>(null)
  const [error, setError] = useState<string | null>(null)
  const logRef = useRef<HTMLDivElement>(null)

  const addLog = (msg: string) => {
    setLog(prev => [...prev, msg])
    setTimeout(() => {
      logRef.current?.scrollTo({ top: logRef.current.scrollHeight, behavior: 'smooth' })
    }, 50)
  }

  const runPipeline = useCallback(async () => {
    setRunning(true)
    setCurrentStep(0)
    setCompletedSteps([])
    setLog([])
    setResult(null)
    setError(null)

    const stepActions: Record<AgentStep, { startMsg: string; endMsg: string; duration: number }> = {
      Intelligence: { startMsg: '🧠 Gathering on-chain intelligence & entity behavior...', endMsg: '✅ Entity profile enriched with transaction patterns', duration: 1200 },
      Compliance: { startMsg: '📋 Running compliance checks (6-factor CI)...', endMsg: '✅ CI computed: 0.42 (PASS)', duration: 1500 },
      ZK: { startMsg: '🔐 Generating ZK proof via Noir circuit...', endMsg: '✅ Proof generated & locally verified', duration: 2000 },
      Settlement: { startMsg: `⚡ Dispatching to ${chain}...`, endMsg: `✅ On-chain tx: stellar_tx_${Math.random().toString(36).slice(2, 10)}`, duration: 1800 },
      Auditor: { startMsg: '📝 Generating audit report via Groq AI...', endMsg: '✅ Audit report generated', duration: 1500 },
    }

    for (let i = 0; i < AGENT_STEPS.length; i++) {
      const step = AGENT_STEPS[i]
      setCurrentStep(i)
      const action = stepActions[step]
      addLog(action.startMsg)
      await new Promise(r => setTimeout(r, action.duration))
      addLog(action.endMsg)
      setCompletedSteps(prev => [...prev, step])
    }

    setResult({
      auditReport: `Audit Report for ${entityId.slice(0, 16)}...
- Compliance Decision: PASS
- CI Score: 0.42
- Risk Level: LOW
- Manifold Cluster: 2
- Chain: ${chain}
- Generated by: Groq LLaMA 3 70B`,
      disclosureLabels: ['COMPLIANCE_INDEX_PASS', 'AML_TOPOLOGY_RISK_PASS', 'JURISDICTION_RISK_PASS'],
      onChainTxHash: `stellar_tx_${Math.random().toString(36).slice(2, 10)}`,
    })

    setCurrentStep(-1)
    setRunning(false)
  }, [entityId, chain])

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <div className="bg-white rounded-2xl w-full max-w-2xl shadow-xl border border-gray-100 max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-100">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-brand-blue to-purple-600 flex items-center justify-center">
              <Brain size={18} className="text-white" />
            </div>
            <div>
              <h2 className="font-bold text-gray-900">Agent Pipeline Orchestrator</h2>
              <p className="text-xs text-gray-500">5-Agent LangGraph compliance pipeline</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1 rounded-lg hover:bg-gray-100">
            <X size={18} className="text-gray-400" />
          </button>
        </div>

        <div className="p-6 space-y-6">
          {!running && !result ? (
            /* Configuration Form */
            <div className="space-y-5">
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-1.5">Entity ID</label>
                <input
                  type="text"
                  placeholder="Wallet address or entity hash"
                  value={entityId}
                  onChange={e => setEntityId(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-white text-sm focus:outline-none focus:ring-2 focus:ring-brand-blue/30 focus:border-brand-blue"
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-1.5">Chain</label>
                  <select
                    value={chain}
                    onChange={e => setChain(e.target.value as any)}
                    className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-white text-sm focus:outline-none focus:ring-2 focus:ring-brand-blue/30 focus:border-brand-blue"
                  >
                    <option value="stellar">Stellar</option>
                    <option value="casper">Casper</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 mb-1.5">Compliance Policy</label>
                  <select
                    value={policy}
                    onChange={e => setPolicy(e.target.value)}
                    className="w-full px-4 py-3 rounded-xl border border-gray-200 bg-white text-sm focus:outline-none focus:ring-2 focus:ring-brand-blue/30 focus:border-brand-blue"
                  >
                    <option value="">Standard KYC</option>
                    <option value="enhanced">Enhanced Due Diligence</option>
                    <option value="simple">Simplified</option>
                  </select>
                </div>
              </div>

              <button
                onClick={runPipeline}
                disabled={!entityId}
                className="btn-primary w-full justify-center text-sm disabled:opacity-60"
              >
                Run Compliance Pipeline <ArrowRight size={14} />
              </button>
            </div>
          ) : (
            <>
              {/* Agent Step Pipeline Visualization */}
              <div className="flex items-center gap-2 justify-between">
                {AGENT_STEPS.map((step, i) => {
                  const Icon = STEP_ICONS[step]
                  const isCompleted = completedSteps.includes(step)
                  const isCurrent = currentStep === i
                  const isPending = !isCompleted && !isCurrent
                  return (
                    <div key={step} className="flex-1">
                      <div className={`flex flex-col items-center gap-2 p-3 rounded-xl border-2 transition-all ${
                        isCompleted
                          ? 'border-emerald-200 bg-emerald-50'
                          : isCurrent
                          ? 'border-brand-blue bg-blue-50'
                          : isPending
                          ? 'border-gray-200 bg-gray-50 opacity-60'
                          : 'border-gray-200'
                      }`}>
                        <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${
                          isCompleted
                            ? 'bg-emerald-100'
                            : isCurrent
                            ? 'bg-brand-blue/10 animate-pulse'
                            : 'bg-gray-100'
                        }`}>
                          {isCompleted ? (
                            <CheckCircle size={16} className="text-emerald-600" />
                          ) : (
                            <Icon size={16} className={isCurrent ? 'text-brand-blue' : 'text-gray-400'} />
                          )}
                        </div>
                        <span className={`text-[10px] font-semibold text-center ${
                          isCompleted ? 'text-emerald-700' : isCurrent ? 'text-brand-blue' : 'text-gray-500'
                        }`}>
                          {step}
                        </span>
                      </div>
                      {i < AGENT_STEPS.length - 1 && (
                        <div className={`h-0.5 mt-2 ${isCompleted ? 'bg-emerald-400' : 'bg-gray-200'}`} />
                      )}
                    </div>
                  )
                })}
              </div>

              {/* Live Log */}
              <div
                ref={logRef}
                className="h-48 overflow-y-auto p-4 rounded-xl bg-gray-900 text-gray-100 font-mono text-xs space-y-1"
              >
                {log.map((msg, i) => (
                  <p key={i} className="leading-relaxed">{msg}</p>
                ))}
                {running && (
                  <p className="text-gray-500 animate-pulse">▋</p>
                )}
              </div>

              {/* Final Result */}
              {result && (
                <div className="space-y-4">
                  <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200">
                    <div className="flex items-center gap-2 mb-3">
                      <CheckCircle size={18} className="text-emerald-600" />
                      <p className="font-semibold text-emerald-900">Pipeline Complete</p>
                    </div>

                    <div className="space-y-3">
                      {/* Audit Report */}
                      <div>
                        <p className="text-xs font-semibold text-gray-500 uppercase mb-1">Audit Report (Groq-generated)</p>
                        <pre className="p-3 rounded-lg bg-white border border-emerald-100 text-xs text-gray-700 whitespace-pre-wrap font-mono">
                          {result.auditReport}
                        </pre>
                      </div>

                      {/* Disclosure Labels */}
                      <div>
                        <p className="text-xs font-semibold text-gray-500 uppercase mb-1">Selective Disclosure Labels</p>
                        <div className="flex flex-wrap gap-2">
                          {result.disclosureLabels.map(label => (
                            <span key={label} className="inline-flex items-center gap-1 text-xs px-2.5 py-1 rounded-full bg-emerald-100 text-emerald-700 font-medium">
                              <CheckCircle size={10} />
                              {label}
                            </span>
                          ))}
                        </div>
                      </div>

                      {/* On-Chain Tx */}
                      <div>
                        <p className="text-xs font-semibold text-gray-500 uppercase mb-1">On-Chain Transaction</p>
                        <p className="font-mono text-sm text-gray-900">{result.onChainTxHash}</p>
                      </div>
                    </div>
                  </div>

                  <div className="flex gap-2">
                    <button onClick={onClose} className="btn-outline flex-1 justify-center text-sm">Close</button>
                    <a href={`/app/runs`} className="btn-primary flex-1 justify-center text-sm">
                      View All Runs <ArrowRight size={12} />
                    </a>
                  </div>
                </div>
              )}

              {error && (
                <div className="p-4 rounded-xl bg-rose-50 border border-rose-200 text-sm text-rose-700">
                  {error}
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  )
}